--- #YAML:1.0
name:               WebService-Strava
version:            0.01
abstract:           Interface to the Strava API version 2
author:
    - Fred Moyer <fred@redhotpenguin.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:  0
    DateTime:    0
    JSON:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
