---
abstract: 'Interface to the Strava API version 2'
author:
  - 'Fred Moyer <fred@redhotpenguin.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Strava
no_index:
  directory:
    - t
    - inc
requires:
  Any::Moose: 0
  Any::URI::Escape: 0
  DateTime: 0
  JSON: 0
version: 0.02
